# The URL the site will be built for
base_url = "https://seijik.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "Seiji Kasahara"
theme = "kodama-theme"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]

# Image of your avatar displayed on the landing page
avatar = "static/img/favicon.ico"
# Image of the favicon
favicon = "static/img/favicon.ico"

# Your email address showed in the contact section
email = "seijik42[at]gmail.com"

# If you don't want to show your contact information in the index
contact_in_index = true

# Additional menu items
# `Name` is what it is displayed, `path` is the url
menu_items = [
    { path = "#contacts", name = "Contact" },
]
